In [1]:
import pandas as pd

In [2]:
df1 = pd.read_csv("fake reviews dataset_modified_file.csv")
df2 = pd.read_csv("Kaggle_ Amazon Product Reviews_modified_file.csv")
df3 = pd.read_csv("/Users/tld/Desktop/CS NLP Project_v2/Datasets/final_dataset_v2.csv")

In [3]:
df1.head()

   label                                               text
0      0  Love this!  Well made, sturdy, and very comfor...
1      0  love it, a great upgrade from the original.  I...
2      0  This pillow saved my back. I love the look and...
3      0  Missing information on how to use it, but it i...
4      0  Very nice set. Good quality. We have had the s...

In [4]:
len(df1)

40432

In [5]:
df2.head()

   label                                               text
0      1  I have bought several of the Vitality canned d...
1      1  Product arrived labeled as Jumbo Salted Peanut...
2      1  This is a confection that has been around a fe...
3      1  If you are looking for the secret ingredient i...
4      1  Great taffy at a great price.  There was a wid...

In [6]:
len(df2)

568454

In [7]:
df3.head()

   label                                               text
0      0  After weeks of using this fitness tool, I can ...
1      0                                       This is one
2      0  This is one of the best purchases I've made re...
3      0                                       After weeks
4      0  After weeks of using this electronic device, I...

In [8]:
len(df3)

275615

In [9]:
merged_df = pd.concat([df1, df2, df3], ignore_index=True)

In [10]:
merged_df.head()

   label                                               text
0      0  Love this!  Well made, sturdy, and very comfor...
1      0  love it, a great upgrade from the original.  I...
2      0  This pillow saved my back. I love the look and...
3      0  Missing information on how to use it, but it i...
4      0  Very nice set. Good quality. We have had the s...

In [11]:
len(merged_df)

884501

In [12]:
label_counts = merged_df['label'].value_counts()

# Display the counts
print("Count of 0s (Computer-Generated Reviews):", label_counts.get(0, 0))
print("Count of 1s (Human-Generated Reviews):", label_counts.get(1, 0))

Count of 0s (Computer-Generated Reviews): 295831
Count of 1s (Human-Generated Reviews): 588670

In [13]:
merged_df = merged_df.sample(frac=1, random_state=42).reset_index(drop=True)

In [14]:
merged_df.head()

   label                                               text
0      1  These are good canned asparagus.  I used to ge...
1      1  I didn't buy this particular one, I bought the...
2      0  Supposedly great as a chew toy. The only probl...
3      1  I wanted to try a new coffee company and found...
4      1  If you don't like ginger, you're not going to ...

In [15]:
merged_df.to_csv("fake reviews dataset_final_v3.csv", index=False)